apiVersion: v1
kind: Namespace
metadata:
  name: wger
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-postgres-pvc
  namespace: wger
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-media-pvc
  namespace: wger
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
