apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-content
  namespace: homepage
data:
  services.yaml: |
    - Homelab:
        - Nextcloud:
            icon: nextcloud
            href: "http://192.168.0.240:30081"
            description: "Dropbox"
        - WireGuard:
            icon: wireguard
            href: "http://192.168.0.17:10086"
            description: "VPN"
        - Proxmox:
            icon: proxmox
            href: "https://192.168.0.167:8006"
            description: "Hypervisor"
        - Kubernetes Dashboard:
            icon: kubernetes
            href: "Not-in-use"
            description: "K8s UI"
        - Pulse:
            icon: grafana
            href: "http://192.168.0.120:7655/hosts"
            description: "Monitoring"

  bookmarks.yaml: |
    - Useful links:
        - GitHub:
            - icon: github
              href: https://github.com/AmundRekve
        - Docs:
            - icon: kubernetes
              href: https://kubernetes.io/docs/
        - Docker:
            - icon: docker
              href: https://hub.docker.com/
