apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-settings
  namespace: homepage
data:
  settings.yaml: |
    title: "Homelab"
    theme: dark
    headerStyle: clean
    allowed_hosts: "*"
    base_url: "http://192.168.0.242:32036"
    layout:
      - Homelab
    authentication:
      enable: false

  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
